version: '3.0'

services:

  img2tags_server:
    image: joshuaze/img2tags:1.0
    networks: ['traefik-net']
    restart: always
    expose:
      - 8081
    labels:
      - "traefik.backend=img2tags"
      - "traefik.frontend.rule=PathPrefixStrip: /img2tags"
      - "traefik.docker.network=traefik-net"
      - "traefik.port=8081"

networks:

  traefik-net:
    external:
      name: traefik-net
