version: '3.0'

services:

  img2tags_server:
    image: joshuaze/img2tags:1.0
    networks: ['traefik-net']
    restart: always
    expose:
      - 8081
    deploy:
      resources:
        limits:
          cpus: '0.80'
          memory: 8000M
        reservations:
          cpus: '0.25'
          memory: 2000M
    labels:
      - "traefik.backend=img2tags"
      - "traefik.frontend.rule=PathPrefixStrip: /img2tags"
      - "traefik.docker.network=traefik-net"
      - "traefik.port=5005"

networks:

  traefik-net:
    external:
      name: traefik-net
